Metrics/LineLength:
  Exclude:
    - Rakefile
    - bin/*
    - db/migrate/*
    - config/initializers/*
    - db/seeds.rb
    - db/schema.rb

Metrics/MethodLength:
  Exclude:
    - db/migrate/*

Style/Documentation:
  Exclude:
    - db/migrate/*
    - test/**/*
    - app/models/application_record.rb
    - app/mailers/application_mailer.rb
    - app/helpers/application_helper.rb
    - app/controllers/application_controller.rb
